os:
  - linux
language: c

before_install:
  - sudo apt-get install qemu-kvm qemu qemu-user-static
  - curl https://api.github.com/repos/vitasdk/autobuilds/releases  | grep browser_download_url | grep linux | head -n 1 | cut -d '"' -f 4 | xargs wget
  - tar xjf *.tar.bz2
  - export VITASDK=$PWD/vitasdk
  - export PATH=$VITASDK/bin:$PATH
  - wget https://releases.linaro.org/archive/15.02/components/toolchain/binaries/arm-linux-gnueabihf/gcc-linaro-4.9-2015.02-3-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xf gcc-linaro-4.9-2015.02-3-x86_64_arm-linux-gnueabihf.tar.xz
  - export PATH=$(pwd)/gcc-linaro-4.9-2015.02-3-x86_64_arm-linux-gnueabihf/bin:$PATH
  - rm gcc-linaro-4.9-2015.02-3-x86_64_arm-linux-gnueabihf.tar.xz
  - git clone https://github.com/JagerDesu/vita-shaders
  - cd vita-shaders
  - make
  - mv *.bin ../
  - cd ..

script:
  - make
  - mkdir -p output/lib
  - mkdir -p output/includes
  - cp shaders/*.h output/includes/
  - cp libvitashaders.a output/lib/
  - tar -zcvf vita-shader-collection.tar.gz -C output .
env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER - $TRAVIS_OS_NAME"
  - git push -q https://$TAGPERM@github.com/frangarcj/vita-shader-collection --tags
deploy:
  provider: releases
  api_key: $OAUTH
  file: "vita-shader-collection.tar.gz"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
